# Generated by Django 2.2.4 on 2020-12-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='field_of_experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(null=True),
        ),
    ]
