# Generated by Django 2.2.4 on 2020-12-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0002_auto_20201223_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
