# Generated by Django 2.2.4 on 2020-12-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_app', '0005_auto_20201223_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='field_of_experience',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
